### ISSUE TITLE
Can date filter support relative time format？

### ISSUE THREAD

**Issue by interjc** [wy-ei/vue-filter#1]
Just like what [moment](http://momentjs.com/docs/#/displaying/fromnow/) / [time ago](http://timeago.yarp.com/) does.
I think it will very helpful, thanks.

**Comment by wy-ei** [comment]
@interjc ok ,thanks for your suggestion. I will consider this feature when

**Comment by wy-ei** [comment]
You can use [vue-moment](https://github.com/brockpetrie/vue-moment). 😃
