### ISSUE TITLE
How to get a specific parameter inside an array?

### ISSUE THREAD

**Issue by visualcookie** [wy-ei/vue-filter#10]
Hi,

for my case I'm using `{{movie.moviebackground | random}}`. Now I want to be able to get the url parameter inside that random array/object element. How would I be able to do it with vue-filter?

**Comment by wy-ei** [comment]
@visualcookie vue-filter don't have a filter help you get a parameter inside an object right now.  I think I should add a filter named `get`, it can help you get a parameter inside an object. 

but, at this time, you can use I `map` filter before `random`, the output of `map` filter is an array which contains the parameter you want, and `random` filter can pick one.

`{{movie.moviebackground | map getAproperty | random}}`

this means you have to write a help function.
