### ISSUE TITLE
[Vue warn]: Failed to resolve filter: substring(0,20) (found in component: <body-content>)

### ISSUE THREAD

**Issue by bonzinho** [wy-ei/vue-filter#12]
Hello,
 I do not know if I'm doing anything wrong, but when I use, for exemple,  the substring (0.20) filter , I get this error: [Vue warn]: Failed to resolve filter: substring (0,20) (Found in component: <body-content>)
can you help me? 
thank you

**Comment by wy-ei** [comment]
@bonzinho The reason is you didn't install the filter correctly. Please see this: [Install](https://github.com/wy-ei/vue-filter#step-1-install-vue-filter). If it can't work please let me know. :)

**Comment by bonzinho** [comment]
Hi again, thanks for quick response,
Sorry im noob with webpack,
and in my file spa.config i do this:
`require('materialize-css');
window.Vue = require('vue');
require('vue-resource');
require('vue-filter');

Vue.http.options.root = appConfig.api_url;
require('./router');`

**Comment by wy-ei** [comment]
```js
var Vue = require('vue');
var VueFilter = require('vue-filter');

Vue.install(VueFilter); // don't forget install
```

Now, I think your problem must be solved. 😃

**Comment by bonzinho** [comment]
I had tried, but it shows me these errors:

[Filter duplication]: A filter named debouncehas has already been installed.
(Anonymous) @ vue-filter.js: 2775
Vue-filter.js: 2775 [filter duplication]: A filter named uppercasehas already been installed.
(Anonymous) @ vue-filter.js: 2775
Vue-filter.js: 2775 [filter duplication]: A filter named lowercasehas already been installed.
(Anonymous) @ vue-filter.js: 2775
Spa.js: 10 Uncaught TypeError: tete.install is not a function
    At Object. <Anonymous> (spa.js: 10)
    At __webpack_require__ (bootstrap efbb9be ...? 3158: 555)
    At fn (bootstrap efbb9be ...? 3158: 86)
    At Object. <Anonymous> (bootstrap efbb9be ...? 3158: 578)
    At __webpack_require__ (bootstrap efbb9be ...? 3158: 555)
    At bootstrap efbb9be ...? 3158: 578
    At bootstrap efbb9be ...? 3158: 578

Thanks anyway

**Comment by bonzinho** [comment]
I had tried, but it shows me these errors:
[Filter duplication]: A filter named debouncehas has already been installed.
(Anonymous) @ vue-filter.js: 2775
Vue-filter.js: 2775 [filter duplication]: A filter named uppercasehas already been installed.
(Anonymous) @ vue-filter.js: 2775
Vue-filter.js: 2775 [filter duplication]: A filter named lowercasehas already been installed.
(Anonymous) @ vue-filter.js: 2775
Spa.js: 10 Uncaught TypeError: Vue.install is not a function
    At Object. <Anonymous> (spa.js: 10)
    At __webpack_require__ (bootstrap efbb9be ...? 3158: 555)
    At fn (bootstrap efbb9be ...? 3158: 86)
    At Object. <Anonymous> (bootstrap efbb9be ...? 3158: 578)
    At __webpack_require__ (bootstrap efbb9be ...? 3158: 555)
    At bootstrap efbb9be ...? 3158: 578
    At bootstrap efbb9be ...? 3158: 578

Thanks anyway

**Comment by wy-ei** [comment]
@bonzinho I don't know why you got those error message. 

> Spa.js: 10 Uncaught TypeError: Vue.install is not a function

`Vue.install` this must be a function. I can check your webpack config. I guess the problem must in there.
