### ISSUE TITLE
v-html="$options.filters.nl2br(text)" doesn't work

### ISSUE THREAD

**Issue by hkmsadek** [wy-ei/vue-filter#17]
When I try to use it like this `<p style="padding: 10px;font-size: 17px;"  v-html="$options.filters.nl2br(opDesc.description)"></p>`  gives errors. 
The error is `"TypeError: _vm.$options.filters.nl2br is not a function"`

**Comment by wy-ei** [comment]
@hkmsadek Sorry, I forgot to publish the update to NPM。 I have published it now, you can reinstall this package.
