### ISSUE TITLE
use webpack to build has an error

### ISSUE THREAD

**Issue by deboyblog** [wy-ei/vue-filter#2]
I use the vue-cli to create my project. 
And then use this vue-filter extend 
when I in dev  every thing is OK, but when I run build there was an ERROR

> ERROR in static\app.e55444684b9e665f7a8f.js from UglifyJs
Unexpected token: operator (>) [./~/.npminstall/vue-filter/0.1.1/vue-filter/vue-filter.js:243,0]

**Comment by wy-ei** [comment]
@deboyblog last time after I update this project, I forget publish it on to npm .sorry about that .  If you install it use `npm install` there will be some error happen. You can install it again now, I have publish the latest version on npm.
