### ISSUE TITLE
为什么我一直不能用呢？

### ISSUE THREAD

**Issue by jacdy** [wy-ei/vue-filter#24]
用了 NPM 安装后，也像下面在main.js 中引用了：
```javascript
import VueFilter from 'vue-filter';
Vue.use(VueFilter);
```
但是不管我用哪个过滤器都会报像以下的错误，不管用 find 或 filter 都是如此：
```html
v-for="img,idx in value|filter(function(image){return !image.isDeleted})"
```
Property or method "filter" is not defined on the instance but referenced during render

**Comment by wy-ei** [comment]
@jacdy 兄弟，filter 不是这样使用的呀。还请你看 vue 的文档，看看 filter 是如何使用的。
