### ISSUE TITLE
Does not wok with v-html for truncating text

### ISSUE THREAD

**Issue by iamtheoleo** [wy-ei/vue-filter#29]
how can i truncate a parsed html with v-html

**Comment by wy-ei** [comment]
@iamtheoleo `v-html` isn't related to filter. It‘s a directive in Vue.js. I guess what you mean is that you  truncated a string and passed it as value for `v-html` but it don't work. I think the problem is not caused by filter and you should check your code.

**Comment by iamtheoleo** [comment]
You miss the whole point, thanks anyway
