### ISSUE TITLE
About the version v0.1.1 on npm

### ISSUE THREAD

**Issue by kennynaoh** [wy-ei/vue-filter#7]
Hello @wy-ei , I am the member of cdnjs project. We want to host this library. There is a question want to ask. I download the old version v0.1.1 on npm, but I can't minify the `vue-filter.js` by myself. Could you help me confirm that. Thanks!

https://github.com/cdnjs/cdnjs/issues/9489

**Comment by wy-ei** [comment]
@kennynaoh sorry , version@0.1.1 is an early version, and I write some ES6 code in it, when we use uglifyjs compress the code, there will be an error . I published version@0.1.2 quickly when I find that problem.  In other word, version@0.1.1 don't working correct. :neutral_face:

**Comment by kennynaoh** [comment]
Thanks @wy-ei , so maybe I need to ignore that version, right?

**Comment by wy-ei** [comment]
@kennynaoh Yes, It is. :grinning:

**Comment by kennynaoh** [comment]
Thanks!
