### ISSUE TITLE
[idea] have a new branch for the removed v1 filters

### ISSUE THREAD

**Issue by ctf0** [wy-ei/vue-filter#9]
what do you think of making a new branch and add back the filters from vue 1 + the current ? 
* so for the v1 users they can only get the extended new ones `master branch`, 
* and for the v2 they get a drop-in replacement for the removed one + the extended `v2 branch with dependency of the master` to avoid replication

**Comment by wy-ei** [comment]
@ctf0 It's a good idea. When I am free I will do this, maybe in this weekend. 😬

**Comment by wy-ei** [comment]
This project([vue2-filters](https://github.com/freearhey/vue2-filters)) do the job, it has all the vue@1 filters.
